In [5]:
import pandas as pd
import glob

In [37]:
fileList = glob.glob('2016/*.csv')

# for files in fileList:
#     df = pd.read_csv(files)

dfs = []

for files in fileList:
    dfs.append(pd.read_csv(files))
    
big_frame = pd.concat(dfs, ignore_index=True)
big_frame

,#,How likely is it that you would recommend the Make School Summer Academy to a friend?,How well are the tutorials paced?,How well is the schedule paced?,How would you rate your overall satisfaction with the Summer Academy this week?,Network ID,Start Date (UTC),Submit Date (UTC),Timestamp,Unnamed: 0,What track are you in?,location,track
0,NaN,NaN,NaN,3,3,NaN,NaN,NaN,8/5/2016 1:39:41,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,3,4,NaN,NaN,NaN,8/5/2016 1:40:47,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,3,4,NaN,NaN,NaN,8/5/2016 1:40:50,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,4,4,NaN,NaN,NaN,8/5/2016 1:42:44,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,4,5,NaN,NaN,NaN,8/5/2016 1:45:13,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,3,4,NaN,NaN,NaN,8/5/2016 1:45:39,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,3,4,NaN,NaN,NaN,8/5/2016 1:49:21,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,3,5,NaN,NaN,NaN,8/8/2016 1:30:34,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,3,5,NaN,NaN,NaN,8/8/2016 1:33:45,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,3,5,NaN,NaN,NaN,8/8/2016 1:49:29,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,3,3,NaN,NaN,NaN,8/8/2016 1:51:00,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,4,3,NaN,NaN,NaN,7/31/2016 1:04:57,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/31/2016 3:38:14,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,1,4,NaN,NaN,NaN,7/31/2016 3:59:43,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,2,4,NaN,NaN,NaN,7/31/2016 4:19:51,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,4,5,NaN,NaN,NaN,7/31/2016 5:14:20,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,3,3,NaN,NaN,NaN,7/31/2016 6:50:12,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,5,5,NaN,NaN,NaN,7/31/2016 15:23:52,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,2,4,NaN,NaN,NaN,7/31/2016 16:49:45,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,4,3,NaN,NaN,NaN,8/1/2016 1:18:47,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,3,5,NaN,NaN,NaN,8/1/2016 1:30:17,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,3,5,NaN,NaN,NaN,8/1/2016 1:30:17,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,4,4,NaN,NaN,NaN,8/1/2016 6:15:10,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,3,4,NaN,NaN,NaN,8/1/2016 7:56:08,NaN,NaN,NaN,NaN
24,NaN,NaN,3.0,NaN,2,NaN,NaN,NaN,6/23/2016 22:24:53,NaN,NaN,NaN,NaN
25,NaN,NaN,3.0,NaN,2,NaN,NaN,NaN,6/27/2016 4:03:03,NaN,NaN,NaN,NaN
26,NaN,NaN,3.0,NaN,3,NaN,NaN,NaN,6/23/2016 22:13:04,NaN,NaN,NaN,NaN
27,NaN,NaN,4.0,NaN,4,NaN,NaN,NaN,6/23/2016 22:09:23,NaN,NaN,NaN,NaN
28,NaN,NaN,4.0,NaN,4,NaN,NaN,NaN,6/23/2016 22:11:39,NaN,NaN,NaN,NaN
29,NaN,NaN,4.0,NaN,4,NaN,NaN,NaN,6/23/2016 22:11:44,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,NaN,NaN,NaN,4,3,NaN,NaN,NaN,7/8/2016 16:40:10,NaN,Apps,NaN,NaN
963,NaN,NaN,NaN,4,4,NaN,NaN,NaN,7/8/2016 13:58:12,NaN,Apps,NaN,NaN
964,NaN,NaN,NaN,4,3,NaN,NaN,NaN,7/8/2016 13:53:19,NaN,Apps,NaN,NaN
965,NaN,NaN,NaN,2,3,NaN,NaN,NaN,7/8/2016 15:59:30,NaN,Apps,NaN,NaN
966,NaN,NaN,NaN,4,5,NaN,NaN,NaN,7/8/2016 16:11:32,NaN,Apps,NaN,NaN
967,NaN,NaN,NaN,5,5,NaN,NaN,NaN,7/8/2016 12:49:05,NaN,Games,NaN,NaN
968,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 12:49:16,NaN,Games,NaN,NaN
969,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 12:47:42,NaN,Games,NaN,NaN
970,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 12:43:44,NaN,Intro,NaN,NaN
971,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 13:55:51,NaN,Apps,NaN,NaN
972,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 14:02:54,NaN,Games,NaN,NaN
973,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 14:29:22,NaN,Games,NaN,NaN
974,NaN,NaN,NaN,2,5,NaN,NaN,NaN,7/9/2016 17:05:33,NaN,Games,NaN,NaN
975,NaN,NaN,NaN,3,3,NaN,NaN,NaN,7/8/2016 16:55:21,NaN,Apps,NaN,NaN
976,NaN,NaN,NaN,3,3,NaN,NaN,NaN,7/8/2016 16:08:13,NaN,Games,NaN,NaN
977,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 13:56:39,NaN,Apps,NaN,NaN
978,NaN,NaN,NaN,2,4,NaN,NaN,NaN,7/8/2016 14:03:35,NaN,Apps,NaN,NaN
979,NaN,NaN,NaN,5,4,NaN,NaN,NaN,7/8/2016 13:51:14,NaN,Games,NaN,NaN
980,NaN,NaN,NaN,4,4,NaN,NaN,NaN,7/8/2016 12:41:10,NaN,Intro,NaN,NaN
981,NaN,NaN,NaN,4,4,NaN,NaN,NaN,7/8/2016 12:41:13,NaN,Intro,NaN,NaN
982,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 12:41:51,NaN,Intro,NaN,NaN
983,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 12:43:35,NaN,Intro,NaN,NaN
984,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 12:45:11,NaN,Intro,NaN,NaN
985,NaN,NaN,NaN,3,4,NaN,NaN,NaN,7/8/2016 12:47:39,NaN,Intro,NaN,NaN
986,NaN,NaN,NaN,4,4,NaN,NaN,NaN,7/8/2016 13:01:58,NaN,Intro,NaN,NaN
987,NaN,NaN,NaN,4,4,NaN,NaN,NaN,7/10/2016 23:44:41,NaN,Games,NaN,NaN
988,NaN,NaN,NaN,#REF!,#REF!,NaN,NaN,NaN,NaN,NaN,Average:,NaN,NaN
989,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 16:41:06,NaN,Apps,NaN,NaN
990,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 13:07:39,NaN,Games,NaN,NaN
991,NaN,NaN,NaN,3,5,NaN,NaN,NaN,7/8/2016 12:45:02,NaN,Intro,NaN,NaN